### ISSUE TITLE
How to define a keyed table

### ISSUE THREAD

**Issue by strikeout** [exxeleron/enterprise-components#58]
Hi! 
At first I want to say: great framework exxeleron team! thank you for open-sourcing this.

Im a beginner in KDB+/Q and would like to know: how can I define keys for a keyed table in dataflow.cfg? Or should I just do something like `xkeys mykey`in every component that works with the table? Also, can I get rid of the `time and `sym column requirements for tables using the tickHF feed?

**Comment by SKolodynski** [comment]
Keyed tables are not supported in dataflow.cfg. Both time and sym column are required in tickHF. I recommend the dist component as the more flexible version of tickHF.

**Comment by strikeout** [comment]
Thank you for the info! 
I've checked out the `dist` component and its very smooth to work with. 
Are there any downsides to using this for _everything_ instead of the `tickHF` component? My use-case is basically an exchange with all the usual components, so I plan to route (immutable) instrument definitions as well as trades, quotes and accounting through `dist`. Would that be a sane approach? Also, how should I work with sectors in the component? I could not get any info out of the documentation. Are they for better (concurrent) journal reading/writing?

**Comment by SKolodynski** [comment]
I personally consider dist to be strictly better than tickHF, but I don't know if any benchmarks have been run so maybe there is a performance penalty for some cases. 
As for sectors the only use case I know to have more than one is when you are working under memory constrains and then you want to splay the table to disk (at eod, directly from a journal) in chunks to decrease your maximal memory usage. 
Exxeleron discussion group at https://groups.google.com/forum/#!forum/exxeleron or StackOverflow (tag with KDB+) are better places to ask these kind of questions.

**Comment by strikeout** [comment]
Thank you for your kind explanation!
